version: '3'
services:
  redis:
    image: redis
  database:
    image: postgres
    volumes:
      - ./tmp/db:/var/lib/postgresql/data
    restart: always
    environment:
      - POSTGRES_PASSWORD=password
  web:
    build: .
    volumes:
      - .:/myapp
      - gem_cache:/gems
    ports:
      - "3000:3000"
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_PASSWORD=password
      - REDIS_URL=redis://redis:6379/0
    depends_on:
      - redis
      - database
volumes:
  db_data:
  gem_cache: